# Generated by Django 3.2.5 on 2021-08-24 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUDENT_NAME', models.CharField(max_length=30)),
                ('STUDENT_MARKS', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('STUDENT_DOB', models.DateField(null='True')),
                ('STUDENT_DOJ', models.DateField(null='True')),
            ],
        ),
    ]
